# Generated by Django 5.2.6 on 2025-09-27 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology (Heart)'), ('Dermatology', 'Dermatology (Skin)'), ('Pediatrics', 'Pediatrics (Children)'), ('Neurology', 'Neurology'), ('General', 'General Medicine'), ('Dentistry', 'Dentistry'), ('Orthopedics', 'Orthopedics'), ('Psychiatry', 'Psychiatry'), ('ENT', 'Ear, Nose & Throat'), ('Ophthalmology', 'Ophthalmology')], max_length=100)),
                ('clinic_location', models.CharField(choices=[('Ramallah', 'Ramallah'), ('Nablus', 'Nablus'), ('Hebron', 'Hebron'), ('Jenin', 'Jenin'), ('Tulkarm', 'Tulkarm'), ('Jerusalem', 'Jerusalem'), ('Gaza', 'Gaza')], max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_approved', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='accounts.user')),
            ],
        ),
    ]
